[project]
name = "lange-python"
version = "0.9.1"
description = "A bundeld set of tools, clients for the lange-suite of tools and more."
authors = [
    { name = "contact@robertlange.me" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "certifi>=2026.0.0",
    "httpx (>=0.28.1,<0.29.0)",
    "websockets (>=12.0,<20.0)",
    "click (>=8.0.0,<9.0.0)",
    "pydantic (>=2.0.0,<3.0.0)",
    "idna>=3.15",
    "ruff>=0.15.20",
    "python-dotenv>=1.2.2",
]

[tool.ty.environment]
python-version = "3.12"

[project.scripts]
lange = "lange.cli:cli"

[tool.poetry]
packages = [{ include = "lange" }]

[tool.poetry.scripts]
lange = "lange.cli:cli"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"

[project.optional-dependencies]

ai-mlx = [
    "huggingface-hub>=0.35.0",
    "tqdm>=4.67.0",
    "mlx-lm",
    "mlx_vlm",
    "mflux==0.18.0",
    "mlx-embeddings==0.1.0",
    "openai>=2.40.0",
    "uvicorn>=0.47.0",
    "fastapi>=0.139.0"
]

ai-cuda = [
    "huggingface-hub>=0.35.0",
    "tqdm>=4.67.0",
    "llama-cpp-python[server]==0.3.32",
    "uvicorn>=0.47.0"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.uv]
environments = ["sys_platform == 'darwin'"]

[dependency-groups]
dev = ["pytest>=8.4.2,<9.0.0"]

[tool.uv.sources]
mlx-lm = { git = "https://github.com/ml-explore/mlx-lm", rev = "ab1806e8f5d6aa035973af194a1b9198ab4754dc" }
mlx-vlm = { git = "https://github.com/Blaizzy/mlx-vlm", rev = "2b7f1a00319fccd2b3b3a6d5fac787234a1cfdef" }
mflux = { git = "https://github.com/filipstrand/mflux", rev = "97ac5e6280e8c65e48a609722229eb9d03ef2cbe" }
