from lange.ai.contracts import (
    AIModelSpecs,
    AiModelRegistration,
    AiModelConfig,
    AiModelVirtualEnvironment,
)

MODEL = AiModelConfig(
    model_name="gemma-4-12b-it",
    model_alias="LL_C_0",
    model_type="LLM",
    size=12,
    quantization="Q8_0",
    enable_thinking=True,
    model_format="gguf",
    model_engine="llama.cpp",
    registration=AiModelRegistration(
        version=2,
        context_length=262144,
        model_name="gemma-4-12b-it",
        model_lang=["en"],
        model_ability=["generate", "chat"],
        model_description="Gemma 4 12B instruction model in GGUF format for llama.cpp.",
        model_family="gemma-4",
        model_specs=[
            AIModelSpecs(
                model_format="gguf",
                model_size_in_billions=12,
                quantization="Q8_0",
                model_id="unsloth/gemma-4-12b-it-GGUF",
                model_hub="huggingface",
                model_uri=None,
                model_revision=None,
                activated_size_in_billions=None,
                model_filename="gemma-4-12b-it-Q8_0.gguf",
            )
        ],
        chat_template=None,
        stop_token_ids=None,
        stop=None,
        reasoning_start_tag=None,
        reasoning_end_tag=None,
        cache_config=None,
        virtualenv=AiModelVirtualEnvironment(
            packages=[
                "llama-cpp-python[server]",
                "uvicorn",
                "huggingface_hub[hf_transfer]",
            ],
            inherit_pip_config=True,
            index_url=None,
            extra_index_url=None,
            find_links=None,
            trusted_host=None,
            no_build_isolation=None,
        ),
        is_builtin=False,
    ),
)
